OSP_APP/OSP_APP/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('accounts.urls')),
    path('', include('account_details.urls')),
    path('', include('fire_vehicle.urls')),
    path('', include('depot_departure.urls')),
    path('', include('depot_tips.urls')),
]

OSP_APP/depot_tips/urls.py
from django.conf.urls.static import static
from django.urls import path
from OSP_APP import settings
from depot_tips.views import DepotTipsView, DepotTipAddView, DepotTipImageAddView

urlpatterns = [
    path('depot_tips/list/', DepotTipsView.as_view(), name='depot_tips'),
    path('depot_tips/add/', DepotTipAddView.as_view(), name='depot_tip_add'),
    path('depot_tips/image/add/', DepotTipImageAddView.as_view(), name='depot_tip_image_add'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

OSP_APP/depot_tips/models.py
from django.db import models


class DepotTip(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class TipsImage(models.Model):
    image = models.ImageField(upload_to='tip_images/')
    depot_tip = models.ForeignKey(DepotTip, on_delete=models.CASCADE)
    

OSP_APP/depot_tips/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from depot_tips.models import DepotTip, TipsImage


# Create your views here.

class DepotTipsView(ListView):
    model = DepotTip
    template_name = 'depot_tips/depot_tip_list.html'
    context_object_name = 'depot_tips'

    def is_member_of_group(self):
        return self.request.user.groups.filter(name='Depot_departure_add').exists()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_member'] = self.is_member_of_group()
        return context


class DepotTipAddView(CreateView):
    model = DepotTip
    template_name = 'depot_tips/depot_tip_add.html'
    fields = ['name', 'description']
    success_url = reverse_lazy('depot_tips')


class DepotTipImageAddView(CreateView):
    model = TipsImage
    template_name = 'depot_tips/depot_tip_image_add.html'
    fields = ['image', 'depot_tip']
    success_url = reverse_lazy('depot_tips')

OSP_APP/depot_tips/templates/depot_tips/depot_tip_add.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_register.css' %}">
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
    <div class="login-container">
        <section class="login-form">
            <h2>Dodanie Porady</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {{ form|crispy }}
                </div>
                <div class="login-button-container">
                    <button class="btn login-button-down" type="submit">Dodaj</button>
                </div>
            </form>
            <button class="btn login-button-down" onclick="window.location.href = '{% url 'home' %}'">Wróć na strone głowna</button>
        </section>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

OSP_APP/depot_tips/templates/depot_tips/depot_tip_image_add.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_register.css' %}">
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
    <div class="login-container">
        <section class="login-form">
            <h2>Dodanie Porady</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {{ form|crispy }}
                </div>
                <div class="login-button-container">
                    <button class="btn login-button-down" type="submit">Dodaj</button>
                </div>
            </form>
            <button class="btn login-button-down" onclick="window.location.href = '{% url 'home' %}'">Wróć na strone głowna</button>
        </section>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

OSP_APP/depot_tips/templates/depot_tips/depot_tip_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
    {% if is_member %}
        <button class="btn" onclick="window.location.href = '{% url 'depot_tip_add' %}'">Dodaj porade</button>
        <button class="btn" onclick="window.location.href = '{% url 'depot_tip_image_add' %}'">Dodaj Zdjecie</button>
    {% endif %}
      {% for tip in depot_tips %}
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">{{ tip }}</h5>
            {% for image in tip.tipsimage_set.all %}
                <img src="{{ image.image.url }}" alt="{{ image.depot_tip.name }} Image">
            {% endfor %}
            <p class="card-text">{{ tip.description }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}